// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rule

import (
	"github.com/rainb0w-clwn/go_auth_limiter/internal/rule"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIStorage
func (_mock *MockIStorage) Create(rule1 rule.Rule) (int, error) {
	ret := _mock.Called(rule1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(rule.Rule) (int, error)); ok {
		return returnFunc(rule1)
	}
	if returnFunc, ok := ret.Get(0).(func(rule.Rule) int); ok {
		r0 = returnFunc(rule1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(rule.Rule) error); ok {
		r1 = returnFunc(rule1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - rule1 rule.Rule
func (_e *MockIStorage_Expecter) Create(rule1 interface{}) *MockIStorage_Create_Call {
	return &MockIStorage_Create_Call{Call: _e.mock.On("Create", rule1)}
}

func (_c *MockIStorage_Create_Call) Run(run func(rule1 rule.Rule)) *MockIStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rule.Rule
		if args[0] != nil {
			arg0 = args[0].(rule.Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStorage_Create_Call) Return(n int, err error) *MockIStorage_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIStorage_Create_Call) RunAndReturn(run func(rule1 rule.Rule) (int, error)) *MockIStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIStorage
func (_mock *MockIStorage) Delete(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockIStorage_Expecter) Delete(id interface{}) *MockIStorage_Delete_Call {
	return &MockIStorage_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockIStorage_Delete_Call) Run(run func(id int)) *MockIStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStorage_Delete_Call) Return(err error) *MockIStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStorage_Delete_Call) RunAndReturn(run func(id int) error) *MockIStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockIStorage
func (_mock *MockIStorage) Find(ip string, ruleType rule.Type) (*rule.Rules, error) {
	ret := _mock.Called(ip, ruleType)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *rule.Rules
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, rule.Type) (*rule.Rules, error)); ok {
		return returnFunc(ip, ruleType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, rule.Type) *rule.Rules); ok {
		r0 = returnFunc(ip, ruleType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rule.Rules)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, rule.Type) error); ok {
		r1 = returnFunc(ip, ruleType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockIStorage_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ip string
//   - ruleType rule.Type
func (_e *MockIStorage_Expecter) Find(ip interface{}, ruleType interface{}) *MockIStorage_Find_Call {
	return &MockIStorage_Find_Call{Call: _e.mock.On("Find", ip, ruleType)}
}

func (_c *MockIStorage_Find_Call) Run(run func(ip string, ruleType rule.Type)) *MockIStorage_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 rule.Type
		if args[1] != nil {
			arg1 = args[1].(rule.Type)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStorage_Find_Call) Return(rules *rule.Rules, err error) *MockIStorage_Find_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockIStorage_Find_Call) RunAndReturn(run func(ip string, ruleType rule.Type) (*rule.Rules, error)) *MockIStorage_Find_Call {
	_c.Call.Return(run)
	return _c
}

// GetForType provides a mock function for the type MockIStorage
func (_mock *MockIStorage) GetForType(ruleType rule.Type) (*rule.Rules, error) {
	ret := _mock.Called(ruleType)

	if len(ret) == 0 {
		panic("no return value specified for GetForType")
	}

	var r0 *rule.Rules
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(rule.Type) (*rule.Rules, error)); ok {
		return returnFunc(ruleType)
	}
	if returnFunc, ok := ret.Get(0).(func(rule.Type) *rule.Rules); ok {
		r0 = returnFunc(ruleType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rule.Rules)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(rule.Type) error); ok {
		r1 = returnFunc(ruleType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_GetForType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForType'
type MockIStorage_GetForType_Call struct {
	*mock.Call
}

// GetForType is a helper method to define mock.On call
//   - ruleType rule.Type
func (_e *MockIStorage_Expecter) GetForType(ruleType interface{}) *MockIStorage_GetForType_Call {
	return &MockIStorage_GetForType_Call{Call: _e.mock.On("GetForType", ruleType)}
}

func (_c *MockIStorage_GetForType_Call) Run(run func(ruleType rule.Type)) *MockIStorage_GetForType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rule.Type
		if args[0] != nil {
			arg0 = args[0].(rule.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStorage_GetForType_Call) Return(rules *rule.Rules, err error) *MockIStorage_GetForType_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockIStorage_GetForType_Call) RunAndReturn(run func(ruleType rule.Type) (*rule.Rules, error)) *MockIStorage_GetForType_Call {
	_c.Call.Return(run)
	return _c
}
