// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appinterfaces

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplication creates a new instance of MockApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplication {
	mock := &MockApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplication is an autogenerated mock type for the Application type
type MockApplication struct {
	mock.Mock
}

type MockApplication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplication) EXPECT() *MockApplication_Expecter {
	return &MockApplication_Expecter{mock: &_m.Mock}
}

// BlackListAdd provides a mock function for the type MockApplication
func (_mock *MockApplication) BlackListAdd(ip string) error {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for BlackListAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_BlackListAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlackListAdd'
type MockApplication_BlackListAdd_Call struct {
	*mock.Call
}

// BlackListAdd is a helper method to define mock.On call
//   - ip string
func (_e *MockApplication_Expecter) BlackListAdd(ip interface{}) *MockApplication_BlackListAdd_Call {
	return &MockApplication_BlackListAdd_Call{Call: _e.mock.On("BlackListAdd", ip)}
}

func (_c *MockApplication_BlackListAdd_Call) Run(run func(ip string)) *MockApplication_BlackListAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_BlackListAdd_Call) Return(err error) *MockApplication_BlackListAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_BlackListAdd_Call) RunAndReturn(run func(ip string) error) *MockApplication_BlackListAdd_Call {
	_c.Call.Return(run)
	return _c
}

// BlackListDelete provides a mock function for the type MockApplication
func (_mock *MockApplication) BlackListDelete(ip string) error {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for BlackListDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_BlackListDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlackListDelete'
type MockApplication_BlackListDelete_Call struct {
	*mock.Call
}

// BlackListDelete is a helper method to define mock.On call
//   - ip string
func (_e *MockApplication_Expecter) BlackListDelete(ip interface{}) *MockApplication_BlackListDelete_Call {
	return &MockApplication_BlackListDelete_Call{Call: _e.mock.On("BlackListDelete", ip)}
}

func (_c *MockApplication_BlackListDelete_Call) Run(run func(ip string)) *MockApplication_BlackListDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_BlackListDelete_Call) Return(err error) *MockApplication_BlackListDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_BlackListDelete_Call) RunAndReturn(run func(ip string) error) *MockApplication_BlackListDelete_Call {
	_c.Call.Return(run)
	return _c
}

// LimitCheck provides a mock function for the type MockApplication
func (_mock *MockApplication) LimitCheck(ip string, login string, password string) (bool, error) {
	ret := _mock.Called(ip, login, password)

	if len(ret) == 0 {
		panic("no return value specified for LimitCheck")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return returnFunc(ip, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = returnFunc(ip, login, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(ip, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplication_LimitCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LimitCheck'
type MockApplication_LimitCheck_Call struct {
	*mock.Call
}

// LimitCheck is a helper method to define mock.On call
//   - ip string
//   - login string
//   - password string
func (_e *MockApplication_Expecter) LimitCheck(ip interface{}, login interface{}, password interface{}) *MockApplication_LimitCheck_Call {
	return &MockApplication_LimitCheck_Call{Call: _e.mock.On("LimitCheck", ip, login, password)}
}

func (_c *MockApplication_LimitCheck_Call) Run(run func(ip string, login string, password string)) *MockApplication_LimitCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApplication_LimitCheck_Call) Return(b bool, err error) *MockApplication_LimitCheck_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockApplication_LimitCheck_Call) RunAndReturn(run func(ip string, login string, password string) (bool, error)) *MockApplication_LimitCheck_Call {
	_c.Call.Return(run)
	return _c
}

// LimitReset provides a mock function for the type MockApplication
func (_mock *MockApplication) LimitReset(ip string, login string) error {
	ret := _mock.Called(ip, login)

	if len(ret) == 0 {
		panic("no return value specified for LimitReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(ip, login)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_LimitReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LimitReset'
type MockApplication_LimitReset_Call struct {
	*mock.Call
}

// LimitReset is a helper method to define mock.On call
//   - ip string
//   - login string
func (_e *MockApplication_Expecter) LimitReset(ip interface{}, login interface{}) *MockApplication_LimitReset_Call {
	return &MockApplication_LimitReset_Call{Call: _e.mock.On("LimitReset", ip, login)}
}

func (_c *MockApplication_LimitReset_Call) Run(run func(ip string, login string)) *MockApplication_LimitReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApplication_LimitReset_Call) Return(err error) *MockApplication_LimitReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_LimitReset_Call) RunAndReturn(run func(ip string, login string) error) *MockApplication_LimitReset_Call {
	_c.Call.Return(run)
	return _c
}

// WhiteListAdd provides a mock function for the type MockApplication
func (_mock *MockApplication) WhiteListAdd(ip string) error {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for WhiteListAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_WhiteListAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhiteListAdd'
type MockApplication_WhiteListAdd_Call struct {
	*mock.Call
}

// WhiteListAdd is a helper method to define mock.On call
//   - ip string
func (_e *MockApplication_Expecter) WhiteListAdd(ip interface{}) *MockApplication_WhiteListAdd_Call {
	return &MockApplication_WhiteListAdd_Call{Call: _e.mock.On("WhiteListAdd", ip)}
}

func (_c *MockApplication_WhiteListAdd_Call) Run(run func(ip string)) *MockApplication_WhiteListAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_WhiteListAdd_Call) Return(err error) *MockApplication_WhiteListAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_WhiteListAdd_Call) RunAndReturn(run func(ip string) error) *MockApplication_WhiteListAdd_Call {
	_c.Call.Return(run)
	return _c
}

// WhiteListDelete provides a mock function for the type MockApplication
func (_mock *MockApplication) WhiteListDelete(ip string) error {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for WhiteListDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_WhiteListDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhiteListDelete'
type MockApplication_WhiteListDelete_Call struct {
	*mock.Call
}

// WhiteListDelete is a helper method to define mock.On call
//   - ip string
func (_e *MockApplication_Expecter) WhiteListDelete(ip interface{}) *MockApplication_WhiteListDelete_Call {
	return &MockApplication_WhiteListDelete_Call{Call: _e.mock.On("WhiteListDelete", ip)}
}

func (_c *MockApplication_WhiteListDelete_Call) Run(run func(ip string)) *MockApplication_WhiteListDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplication_WhiteListDelete_Call) Return(err error) *MockApplication_WhiteListDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_WhiteListDelete_Call) RunAndReturn(run func(ip string) error) *MockApplication_WhiteListDelete_Call {
	_c.Call.Return(run)
	return _c
}
