// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package limiter

import (
	"github.com/rainb0w-clwn/go_auth_limiter/internal/limiter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// GetLimits provides a mock function for the type MockIStorage
func (_mock *MockIStorage) GetLimits() (*limiter.Limits, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLimits")
	}

	var r0 *limiter.Limits
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*limiter.Limits, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *limiter.Limits); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*limiter.Limits)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_GetLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimits'
type MockIStorage_GetLimits_Call struct {
	*mock.Call
}

// GetLimits is a helper method to define mock.On call
func (_e *MockIStorage_Expecter) GetLimits() *MockIStorage_GetLimits_Call {
	return &MockIStorage_GetLimits_Call{Call: _e.mock.On("GetLimits")}
}

func (_c *MockIStorage_GetLimits_Call) Run(run func()) *MockIStorage_GetLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIStorage_GetLimits_Call) Return(limits *limiter.Limits, err error) *MockIStorage_GetLimits_Call {
	_c.Call.Return(limits, err)
	return _c
}

func (_c *MockIStorage_GetLimits_Call) RunAndReturn(run func() (*limiter.Limits, error)) *MockIStorage_GetLimits_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimitsByTypes provides a mock function for the type MockIStorage
func (_mock *MockIStorage) GetLimitsByTypes(strings []string) (*limiter.Limits, error) {
	ret := _mock.Called(strings)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitsByTypes")
	}

	var r0 *limiter.Limits
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (*limiter.Limits, error)); ok {
		return returnFunc(strings)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) *limiter.Limits); ok {
		r0 = returnFunc(strings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*limiter.Limits)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_GetLimitsByTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimitsByTypes'
type MockIStorage_GetLimitsByTypes_Call struct {
	*mock.Call
}

// GetLimitsByTypes is a helper method to define mock.On call
//   - strings []string
func (_e *MockIStorage_Expecter) GetLimitsByTypes(strings interface{}) *MockIStorage_GetLimitsByTypes_Call {
	return &MockIStorage_GetLimitsByTypes_Call{Call: _e.mock.On("GetLimitsByTypes", strings)}
}

func (_c *MockIStorage_GetLimitsByTypes_Call) Run(run func(strings []string)) *MockIStorage_GetLimitsByTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStorage_GetLimitsByTypes_Call) Return(limits *limiter.Limits, err error) *MockIStorage_GetLimitsByTypes_Call {
	_c.Call.Return(limits, err)
	return _c
}

func (_c *MockIStorage_GetLimitsByTypes_Call) RunAndReturn(run func(strings []string) (*limiter.Limits, error)) *MockIStorage_GetLimitsByTypes_Call {
	_c.Call.Return(run)
	return _c
}
