// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/limiter/AuthLimiter.proto

package proto

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/meshapi/grpc-api-gateway/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhiteListAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNet         string                 `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhiteListAddRequest) Reset() {
	*x = WhiteListAddRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteListAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListAddRequest) ProtoMessage() {}

func (x *WhiteListAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListAddRequest.ProtoReflect.Descriptor instead.
func (*WhiteListAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{0}
}

func (x *WhiteListAddRequest) GetIpNet() string {
	if x != nil {
		return x.IpNet
	}
	return ""
}

type WhiteListDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNet         string                 `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhiteListDeleteRequest) Reset() {
	*x = WhiteListDeleteRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteListDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListDeleteRequest) ProtoMessage() {}

func (x *WhiteListDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListDeleteRequest.ProtoReflect.Descriptor instead.
func (*WhiteListDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{1}
}

func (x *WhiteListDeleteRequest) GetIpNet() string {
	if x != nil {
		return x.IpNet
	}
	return ""
}

type BlackListAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNet         string                 `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackListAddRequest) Reset() {
	*x = BlackListAddRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackListAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListAddRequest) ProtoMessage() {}

func (x *BlackListAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListAddRequest.ProtoReflect.Descriptor instead.
func (*BlackListAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{2}
}

func (x *BlackListAddRequest) GetIpNet() string {
	if x != nil {
		return x.IpNet
	}
	return ""
}

type BlackListDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpNet         string                 `protobuf:"bytes,1,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackListDeleteRequest) Reset() {
	*x = BlackListDeleteRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackListDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListDeleteRequest) ProtoMessage() {}

func (x *BlackListDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListDeleteRequest.ProtoReflect.Descriptor instead.
func (*BlackListDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{3}
}

func (x *BlackListDeleteRequest) GetIpNet() string {
	if x != nil {
		return x.IpNet
	}
	return ""
}

type BucketResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketResetRequest) Reset() {
	*x = BucketResetRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResetRequest) ProtoMessage() {}

func (x *BucketResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResetRequest.ProtoReflect.Descriptor instead.
func (*BucketResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{4}
}

func (x *BucketResetRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *BucketResetRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LimitCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitCheckRequest) Reset() {
	*x = LimitCheckRequest{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitCheckRequest) ProtoMessage() {}

func (x *LimitCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitCheckRequest.ProtoReflect.Descriptor instead.
func (*LimitCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{5}
}

func (x *LimitCheckRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LimitCheckRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LimitCheckRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type WhiteListAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhiteListAddResponse) Reset() {
	*x = WhiteListAddResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteListAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListAddResponse) ProtoMessage() {}

func (x *WhiteListAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListAddResponse.ProtoReflect.Descriptor instead.
func (*WhiteListAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{6}
}

type WhiteListDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhiteListDeleteResponse) Reset() {
	*x = WhiteListDeleteResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhiteListDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteListDeleteResponse) ProtoMessage() {}

func (x *WhiteListDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteListDeleteResponse.ProtoReflect.Descriptor instead.
func (*WhiteListDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{7}
}

type BlackListAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackListAddResponse) Reset() {
	*x = BlackListAddResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackListAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListAddResponse) ProtoMessage() {}

func (x *BlackListAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListAddResponse.ProtoReflect.Descriptor instead.
func (*BlackListAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{8}
}

type BlackListDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackListDeleteResponse) Reset() {
	*x = BlackListDeleteResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackListDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListDeleteResponse) ProtoMessage() {}

func (x *BlackListDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListDeleteResponse.ProtoReflect.Descriptor instead.
func (*BlackListDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{9}
}

type BucketResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketResetResponse) Reset() {
	*x = BucketResetResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResetResponse) ProtoMessage() {}

func (x *BucketResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResetResponse.ProtoReflect.Descriptor instead.
func (*BucketResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{10}
}

type LimitCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitCheckResponse) Reset() {
	*x = LimitCheckResponse{}
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitCheckResponse) ProtoMessage() {}

func (x *LimitCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_AuthLimiter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitCheckResponse.ProtoReflect.Descriptor instead.
func (*LimitCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_AuthLimiter_proto_rawDescGZIP(), []int{11}
}

func (x *LimitCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_proto_limiter_AuthLimiter_proto protoreflect.FileDescriptor

const file_proto_limiter_AuthLimiter_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/limiter/AuthLimiter.proto\x12\vAuthLimiter\x1a!meshapi/gateway/annotations.proto\x1a\x1bbuf/validate/validate.proto\"\x80\x01\n" +
	"\x13WhiteListAddRequest\x12\\\n" +
	"\x06ip_net\x18\x01 \x01(\tBE\xbaHB\xc8\x01\x01r=2;^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$R\x05ipNet:\v\xbaJ\bj\x06ip_net\"\x83\x01\n" +
	"\x16WhiteListDeleteRequest\x12\\\n" +
	"\x06ip_net\x18\x01 \x01(\tBE\xbaHB\xc8\x01\x01r=2;^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$R\x05ipNet:\v\xbaJ\bj\x06ip_net\"\x80\x01\n" +
	"\x13BlackListAddRequest\x12\\\n" +
	"\x06ip_net\x18\x01 \x01(\tBE\xbaHB\xc8\x01\x01r=2;^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$R\x05ipNet:\v\xbaJ\bj\x06ip_net\"\x83\x01\n" +
	"\x16BlackListDeleteRequest\x12\\\n" +
	"\x06ip_net\x18\x01 \x01(\tBE\xbaHB\xc8\x01\x01r=2;^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$R\x05ipNet:\v\xbaJ\bj\x06ip_net\"y\n" +
	"\x12BucketResetRequest\x12-\n" +
	"\x05login\x18\x01 \x01(\tB\x17\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x01\xbaJ\a\xa0\x01\x80\x01\xa8\x01\x01R\x05login\x12$\n" +
	"\x02ip\x18\x02 \x01(\tB\x14\xbaH\a\xc8\x01\x01r\x02p\x01\xbaJ\a\xc2\x02\x04ipv4R\x02ip:\x0e\xbaJ\vj\x05loginj\x02ip\"\xb7\x01\n" +
	"\x11LimitCheckRequest\x12-\n" +
	"\x05login\x18\x01 \x01(\tB\x17\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x01\xbaJ\a\xa0\x01\x80\x01\xa8\x01\x01R\x05login\x123\n" +
	"\bpassword\x18\x02 \x01(\tB\x17\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x02\xbaJ\a\xa0\x01\x80\x02\xa8\x01\x01R\bpassword\x12$\n" +
	"\x02ip\x18\x03 \x01(\tB\x14\xbaH\a\xc8\x01\x01r\x02p\x01\xbaJ\a\xc2\x02\x04ipv4R\x02ip:\x18\xbaJ\x15j\x05loginj\bpasswordj\x02ip\"\x16\n" +
	"\x14WhiteListAddResponse\"\x19\n" +
	"\x17WhiteListDeleteResponse\"\x16\n" +
	"\x14BlackListAddResponse\"\x19\n" +
	"\x17BlackListDeleteResponse\"\x15\n" +
	"\x13BucketResetResponse\".\n" +
	"\x12LimitCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\x9c\a\n" +
	"\vAuthLimiter\x12\x92\x01\n" +
	"\fWhiteListAdd\x12 .AuthLimiter.WhiteListAddRequest\x1a!.AuthLimiter.WhiteListAddResponse\"=\xb2J\x0fB\x01*\"\n" +
	"/whitelist\xbaJ(\n" +
	"\tWhitelist\x12\x1bAdd IP network to whitelist\x12\x9d\x01\n" +
	"\x0fWhiteListDelete\x12#.AuthLimiter.WhiteListDeleteRequest\x1a$.AuthLimiter.WhiteListDeleteResponse\"?\xb2J\f*\n" +
	"/whitelist\xbaJ-\n" +
	"\tWhitelist\x12 Remove IP network from whitelist\x12\x92\x01\n" +
	"\fBlackListAdd\x12 .AuthLimiter.BlackListAddRequest\x1a!.AuthLimiter.BlackListAddResponse\"=\xb2J\x0fB\x01*\"\n" +
	"/blacklist\xbaJ(\n" +
	"\tBlacklist\x12\x1bAdd IP network to blacklist\x12\x9d\x01\n" +
	"\x0fBlackListDelete\x12#.AuthLimiter.BlackListDeleteRequest\x1a$.AuthLimiter.BlackListDeleteResponse\"?\xb2J\f*\n" +
	"/blacklist\xbaJ-\n" +
	"\tBlacklist\x12 Remove IP network from blacklist\x12\x85\x01\n" +
	"\vBucketReset\x12\x1f.AuthLimiter.BucketResetRequest\x1a .AuthLimiter.BucketResetResponse\"3\xb2J\vB\x01*\"\x06/reset\xbaJ\"\n" +
	"\aLimiter\x12\x17Reset rate limit bucket\x12\x9a\x01\n" +
	"\n" +
	"LimitCheck\x12\x1e.AuthLimiter.LimitCheckRequest\x1a\x1f.AuthLimiter.LimitCheckResponse\"K\xb2J\vB\x01*\"\x06/check\xbaJ:\n" +
	"\aLimiter\x12/Check whether authentication attempt is allowedB\xcd\x01\xbaJ\x9a\x01\n" +
	"S\n" +
	"\x10Auth Limiter API\x1a8Authentication rate limiter and abuse protection service:\x051.0.0\x12\x1e\n" +
	"\x15http://localhost:8888\x12\x05Local:\v\n" +
	"\tWhitelist:\v\n" +
	"\tBlacklist:\t\n" +
	"\aLimiterZ-github.com/rainb0w-clwn/go_auth_limiter/protob\x06proto3"

var (
	file_proto_limiter_AuthLimiter_proto_rawDescOnce sync.Once
	file_proto_limiter_AuthLimiter_proto_rawDescData []byte
)

func file_proto_limiter_AuthLimiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_AuthLimiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_AuthLimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_AuthLimiter_proto_rawDesc), len(file_proto_limiter_AuthLimiter_proto_rawDesc)))
	})
	return file_proto_limiter_AuthLimiter_proto_rawDescData
}

var file_proto_limiter_AuthLimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_limiter_AuthLimiter_proto_goTypes = []any{
	(*WhiteListAddRequest)(nil),     // 0: AuthLimiter.WhiteListAddRequest
	(*WhiteListDeleteRequest)(nil),  // 1: AuthLimiter.WhiteListDeleteRequest
	(*BlackListAddRequest)(nil),     // 2: AuthLimiter.BlackListAddRequest
	(*BlackListDeleteRequest)(nil),  // 3: AuthLimiter.BlackListDeleteRequest
	(*BucketResetRequest)(nil),      // 4: AuthLimiter.BucketResetRequest
	(*LimitCheckRequest)(nil),       // 5: AuthLimiter.LimitCheckRequest
	(*WhiteListAddResponse)(nil),    // 6: AuthLimiter.WhiteListAddResponse
	(*WhiteListDeleteResponse)(nil), // 7: AuthLimiter.WhiteListDeleteResponse
	(*BlackListAddResponse)(nil),    // 8: AuthLimiter.BlackListAddResponse
	(*BlackListDeleteResponse)(nil), // 9: AuthLimiter.BlackListDeleteResponse
	(*BucketResetResponse)(nil),     // 10: AuthLimiter.BucketResetResponse
	(*LimitCheckResponse)(nil),      // 11: AuthLimiter.LimitCheckResponse
}
var file_proto_limiter_AuthLimiter_proto_depIdxs = []int32{
	0,  // 0: AuthLimiter.AuthLimiter.WhiteListAdd:input_type -> AuthLimiter.WhiteListAddRequest
	1,  // 1: AuthLimiter.AuthLimiter.WhiteListDelete:input_type -> AuthLimiter.WhiteListDeleteRequest
	2,  // 2: AuthLimiter.AuthLimiter.BlackListAdd:input_type -> AuthLimiter.BlackListAddRequest
	3,  // 3: AuthLimiter.AuthLimiter.BlackListDelete:input_type -> AuthLimiter.BlackListDeleteRequest
	4,  // 4: AuthLimiter.AuthLimiter.BucketReset:input_type -> AuthLimiter.BucketResetRequest
	5,  // 5: AuthLimiter.AuthLimiter.LimitCheck:input_type -> AuthLimiter.LimitCheckRequest
	6,  // 6: AuthLimiter.AuthLimiter.WhiteListAdd:output_type -> AuthLimiter.WhiteListAddResponse
	7,  // 7: AuthLimiter.AuthLimiter.WhiteListDelete:output_type -> AuthLimiter.WhiteListDeleteResponse
	8,  // 8: AuthLimiter.AuthLimiter.BlackListAdd:output_type -> AuthLimiter.BlackListAddResponse
	9,  // 9: AuthLimiter.AuthLimiter.BlackListDelete:output_type -> AuthLimiter.BlackListDeleteResponse
	10, // 10: AuthLimiter.AuthLimiter.BucketReset:output_type -> AuthLimiter.BucketResetResponse
	11, // 11: AuthLimiter.AuthLimiter.LimitCheck:output_type -> AuthLimiter.LimitCheckResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_AuthLimiter_proto_init() }
func file_proto_limiter_AuthLimiter_proto_init() {
	if File_proto_limiter_AuthLimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_AuthLimiter_proto_rawDesc), len(file_proto_limiter_AuthLimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_AuthLimiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_AuthLimiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_AuthLimiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_AuthLimiter_proto = out.File
	file_proto_limiter_AuthLimiter_proto_goTypes = nil
	file_proto_limiter_AuthLimiter_proto_depIdxs = nil
}
