// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: proto/limiter/AuthLimiter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthLimiter_WhiteListAdd_FullMethodName    = "/AuthLimiter.AuthLimiter/WhiteListAdd"
	AuthLimiter_WhiteListDelete_FullMethodName = "/AuthLimiter.AuthLimiter/WhiteListDelete"
	AuthLimiter_BlackListAdd_FullMethodName    = "/AuthLimiter.AuthLimiter/BlackListAdd"
	AuthLimiter_BlackListDelete_FullMethodName = "/AuthLimiter.AuthLimiter/BlackListDelete"
	AuthLimiter_BucketReset_FullMethodName     = "/AuthLimiter.AuthLimiter/BucketReset"
	AuthLimiter_LimitCheck_FullMethodName      = "/AuthLimiter.AuthLimiter/LimitCheck"
)

// AuthLimiterClient is the client API for AuthLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// /////////////////////////////////////////////////////////
// Service
// ////////////////////////////////////////////////////////
type AuthLimiterClient interface {
	WhiteListAdd(ctx context.Context, in *WhiteListAddRequest, opts ...grpc.CallOption) (*WhiteListAddResponse, error)
	WhiteListDelete(ctx context.Context, in *WhiteListDeleteRequest, opts ...grpc.CallOption) (*WhiteListDeleteResponse, error)
	BlackListAdd(ctx context.Context, in *BlackListAddRequest, opts ...grpc.CallOption) (*BlackListAddResponse, error)
	BlackListDelete(ctx context.Context, in *BlackListDeleteRequest, opts ...grpc.CallOption) (*BlackListDeleteResponse, error)
	BucketReset(ctx context.Context, in *BucketResetRequest, opts ...grpc.CallOption) (*BucketResetResponse, error)
	LimitCheck(ctx context.Context, in *LimitCheckRequest, opts ...grpc.CallOption) (*LimitCheckResponse, error)
}

type authLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthLimiterClient(cc grpc.ClientConnInterface) AuthLimiterClient {
	return &authLimiterClient{cc}
}

func (c *authLimiterClient) WhiteListAdd(ctx context.Context, in *WhiteListAddRequest, opts ...grpc.CallOption) (*WhiteListAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhiteListAddResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_WhiteListAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLimiterClient) WhiteListDelete(ctx context.Context, in *WhiteListDeleteRequest, opts ...grpc.CallOption) (*WhiteListDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhiteListDeleteResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_WhiteListDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLimiterClient) BlackListAdd(ctx context.Context, in *BlackListAddRequest, opts ...grpc.CallOption) (*BlackListAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlackListAddResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_BlackListAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLimiterClient) BlackListDelete(ctx context.Context, in *BlackListDeleteRequest, opts ...grpc.CallOption) (*BlackListDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlackListDeleteResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_BlackListDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLimiterClient) BucketReset(ctx context.Context, in *BucketResetRequest, opts ...grpc.CallOption) (*BucketResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketResetResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_BucketReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLimiterClient) LimitCheck(ctx context.Context, in *LimitCheckRequest, opts ...grpc.CallOption) (*LimitCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LimitCheckResponse)
	err := c.cc.Invoke(ctx, AuthLimiter_LimitCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthLimiterServer is the server API for AuthLimiter service.
// All implementations must embed UnimplementedAuthLimiterServer
// for forward compatibility.
//
// /////////////////////////////////////////////////////////
// Service
// ////////////////////////////////////////////////////////
type AuthLimiterServer interface {
	WhiteListAdd(context.Context, *WhiteListAddRequest) (*WhiteListAddResponse, error)
	WhiteListDelete(context.Context, *WhiteListDeleteRequest) (*WhiteListDeleteResponse, error)
	BlackListAdd(context.Context, *BlackListAddRequest) (*BlackListAddResponse, error)
	BlackListDelete(context.Context, *BlackListDeleteRequest) (*BlackListDeleteResponse, error)
	BucketReset(context.Context, *BucketResetRequest) (*BucketResetResponse, error)
	LimitCheck(context.Context, *LimitCheckRequest) (*LimitCheckResponse, error)
	mustEmbedUnimplementedAuthLimiterServer()
}

// UnimplementedAuthLimiterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthLimiterServer struct{}

func (UnimplementedAuthLimiterServer) WhiteListAdd(context.Context, *WhiteListAddRequest) (*WhiteListAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhiteListAdd not implemented")
}
func (UnimplementedAuthLimiterServer) WhiteListDelete(context.Context, *WhiteListDeleteRequest) (*WhiteListDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhiteListDelete not implemented")
}
func (UnimplementedAuthLimiterServer) BlackListAdd(context.Context, *BlackListAddRequest) (*BlackListAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlackListAdd not implemented")
}
func (UnimplementedAuthLimiterServer) BlackListDelete(context.Context, *BlackListDeleteRequest) (*BlackListDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlackListDelete not implemented")
}
func (UnimplementedAuthLimiterServer) BucketReset(context.Context, *BucketResetRequest) (*BucketResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BucketReset not implemented")
}
func (UnimplementedAuthLimiterServer) LimitCheck(context.Context, *LimitCheckRequest) (*LimitCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LimitCheck not implemented")
}
func (UnimplementedAuthLimiterServer) mustEmbedUnimplementedAuthLimiterServer() {}
func (UnimplementedAuthLimiterServer) testEmbeddedByValue()                     {}

// UnsafeAuthLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthLimiterServer will
// result in compilation errors.
type UnsafeAuthLimiterServer interface {
	mustEmbedUnimplementedAuthLimiterServer()
}

func RegisterAuthLimiterServer(s grpc.ServiceRegistrar, srv AuthLimiterServer) {
	// If the following call panics, it indicates UnimplementedAuthLimiterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthLimiter_ServiceDesc, srv)
}

func _AuthLimiter_WhiteListAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhiteListAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).WhiteListAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_WhiteListAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).WhiteListAdd(ctx, req.(*WhiteListAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLimiter_WhiteListDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhiteListDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).WhiteListDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_WhiteListDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).WhiteListDelete(ctx, req.(*WhiteListDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLimiter_BlackListAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackListAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).BlackListAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_BlackListAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).BlackListAdd(ctx, req.(*BlackListAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLimiter_BlackListDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackListDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).BlackListDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_BlackListDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).BlackListDelete(ctx, req.(*BlackListDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLimiter_BucketReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).BucketReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_BucketReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).BucketReset(ctx, req.(*BucketResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLimiter_LimitCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLimiterServer).LimitCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLimiter_LimitCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLimiterServer).LimitCheck(ctx, req.(*LimitCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthLimiter_ServiceDesc is the grpc.ServiceDesc for AuthLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthLimiter.AuthLimiter",
	HandlerType: (*AuthLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhiteListAdd",
			Handler:    _AuthLimiter_WhiteListAdd_Handler,
		},
		{
			MethodName: "WhiteListDelete",
			Handler:    _AuthLimiter_WhiteListDelete_Handler,
		},
		{
			MethodName: "BlackListAdd",
			Handler:    _AuthLimiter_BlackListAdd_Handler,
		},
		{
			MethodName: "BlackListDelete",
			Handler:    _AuthLimiter_BlackListDelete_Handler,
		},
		{
			MethodName: "BucketReset",
			Handler:    _AuthLimiter_BucketReset_Handler,
		},
		{
			MethodName: "LimitCheck",
			Handler:    _AuthLimiter_LimitCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/limiter/AuthLimiter.proto",
}
